# Generated by Django 3.0.7 on 2020-08-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200805_1809'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
