# Generated by Django 3.0.7 on 2020-08-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200809_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
